export const INDEX = '/pages/index/index'
export const SEARCH_CLASS = '/pages/search-class/search-class'
export const CREATE_CLASS = '/pages/create-class/create-class'
export const CLASS_DETAIL = '/pages/class-detail/class-detail'
export const JOIN_CLASS = '/pages/join-class/join-class'
export const CLASS_MAP = '/pages/class-map/class-map'
