export const CLASSSTORAGE = 'classDetail'
export const USERSTORAGE = 'userInfo'
export const JOININFO = 'joinInfo'
export const JOINUSERS = 'joinUsers'
export const LIMITSTORAGE = 'limitInfo'
export const COLLECT_TOOLTIP_STORAGE = 'collectTooltip'
export const CLASS_SHARE_TOOLTIP_STORAGE = 'classShareTooltip'