export const AUTH_SUCCESS = '授权成功'
export const CREATE_SUCCESS = '创建成功'
export const ILLEGAL_TOKEN = '口令至少 6 位，且至少包含字母和数字'
export const CHECK_TOKEN_LOADING = '检查口令...'
export const OCCUPY_TOKEN = '口令已被占用'
export const EMPTY_CREATOR = '请输入创建者姓名或昵称'
export const EMPTY_CLASSNAME = '请输入班级名称'
export const ILLEGAL_COUNT = '班级人数需>0且≤100'
export const EMPTY_IMAGE = '请上传一张班级照片'
export const LOADING = '加载中...'
export const EXPECTION = '网络错误，请稍后重试'

