export const AUTH_SUCCESS = '授权成功'
export const CREATE_SUCCESS = '创建成功'
export const ILLEGAL_TOKEN = '口令至少 6 位，且至少包含字母和数字'
export const CHECK_TOKEN_LOADING = '检查口令...'
export const OCCUPY_TOKEN = '口令已被占用'
export const EMPTY_CREATOR = '请输入创建者姓名或昵称'
export const EMPTY_CLASSNAME = '请输入班级名称'
export const ILLEGAL_COUNT = '班级人数需>0且≤100'
export const EMPTY_IMAGE = '请上传一张班级照片'
export const LOADING = '加载中...'
export const EXPECTION = '网络异常，请稍后重试'
export const SEARCHING = '搜索中...'
export const SEARCH_EMPTY = '未找到内容，请检查口令是否输入正确'
export const QUIT_SUCCESS = '退出成功'

export const EMPTY_NAME = '请输入您的姓名或昵称'
export const ILLEGAL_PHONE = '请输入正确格式的电话号码'
export const EMPTY_PLAGE = '请输入学校或单位名称'
export const EMPTY_ADDRESS = '请选择一个地址'
export const WRONG_TOKEN = '口令错误'

export const CANCEL_SELECT = '取消选择'
export const JOIN_SUCCESS ='加入成功'

export const CREATING = '创建中...'
export const UPDATING = '修改中...'
export const IMG_UPLOADING = '图片上传...'
export const SAVE_SUCCESS = '信息保存成功'
export const UPDATE_SUCCESS = '信息更新成功'

export const CHECK_CONTENT = '内容检测...'
export const CHECK_IMAGE = '图片检测...'

export const THIRD_PARTY = '支付需要跳转到第三方平台进行'

export const PAY_SUCCESS = '支付成功'
